export interface AgentEvent {
  type: "log" | "status" | "error" | "complete";
  stream?: "stdout" | "stderr" | "system";
  content?: string;
  exitCode?: number;
}

export interface EngineOptions {
  runId: string;
  signal?: AbortSignal;
  model?: string;
  /** Virtual key generated by LiteLLM for this run. Undefined when LiteLLM is disabled. */
  litellmKey?: string;
  /** LiteLLM proxy base URL (e.g. http://localhost:4000). Undefined when LiteLLM is disabled. */
  litellmBaseUrl?: string;
  /** Native AI provider API keys from DB settings (used when LiteLLM is disabled). */
  nativeApiKeys?: {
    gemini?: string;
    anthropic?: string;
    openai?: string;
  };
}

export interface AgentEngine {
  /** Unique identifier, e.g., "claude-code" */
  name: string;

  /** Human-readable label */
  displayName: string;

  /** Check if the CLI tool is installed and accessible */
  isAvailable(): Promise<boolean>;

  /** Get CLI version string, e.g. "1.2.3". Returns null if not available. */
  getVersion?(): Promise<string | null>;

  /** Optional readiness issue when the engine is installed but not fully configured. */
  getSetupIssue?(): Promise<string | null>;

  /** List available models by querying the CLI. Returns [] if not supported. */
  listModels(): Promise<string[]>;

  /**
   * Execute a task in the given directory.
   * Yields events as the agent works.
   */
  execute(prompt: string, workdir: string, options: EngineOptions): AsyncGenerator<AgentEvent>;

  /** Kill a running agent process */
  abort(runId: string): void;

  /** Send input to a running agent's stdin */
  sendInput(runId: string, input: string): boolean;
}
