import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentRun, Task } from "@vibe-code/shared";
import type { Db } from "../../db";
import type { GitService } from "../../git/git-service";

const CONTEXT_DIR = ".vibe-code/context";

export interface HarnessContextPaths {
  progressMd: string;
  taskJson: string;
}

/**
 * Writes two harness context files into the worktree before the agent runs.
 *
 * `.vibe-code/context/PROGRESS.md` — Human-readable session context:
 *   task description, previous run notes, matched skills, recent git history.
 *
 * `.vibe-code/context/TASK.json` — Structured task metadata for agents that
 *   prefer machine-readable input.
 *
 * Both files are gitignored via the caller's ensureGitignoreEntry pattern.
 * Returns the absolute paths written so the executor can clean them up.
 */
export async function writeHarnessContext(
  task: Task,
  run: AgentRun,
  wtPath: string,
  db: Db,
  _git: GitService
): Promise<string[]> {
  const contextDir = join(wtPath, CONTEXT_DIR);
  await mkdir(contextDir, { recursive: true });

  const progressPath = join(contextDir, "PROGRESS.md");
  const taskJsonPath = join(contextDir, "TASK.json");

  // ── recent git history ──────────────────────────────────────────────────
  let recentCommits = "(no commit history yet)";
  try {
    const proc = Bun.spawn(["git", "log", "--oneline", "-10"], {
      cwd: wtPath,
      stdout: "pipe",
      stderr: "pipe",
    });
    await proc.exited;
    const text = await new Response(proc.stdout).text();
    if (text.trim()) recentCommits = text.trim();
  } catch {
    /* best-effort */
  }

  // ── previous run notes from task.notes ─────────────────────────────────
  const previousNotes = task.notes?.trim() || "(no previous notes)";

  // ── matched skills on this run ──────────────────────────────────────────
  const currentRun = db.runs.getById(run.id);
  let matchedSkillNames: string[] = [];
  try {
    matchedSkillNames = JSON.parse(currentRun?.matchedSkills ?? "[]") as string[];
  } catch {
    matchedSkillNames = [];
  }
  const skillsLine = matchedSkillNames.length > 0 ? matchedSkillNames.join(", ") : "(none matched)";

  // ── PROGRESS.md ─────────────────────────────────────────────────────────
  const progressContent = [
    "# Session Context",
    "",
    `## Task: ${task.title}`,
    "",
    task.description?.trim()
      ? `### Description\n${task.description.trim()}`
      : "### Description\n(not provided)",
    "",
    `### Status\n${task.status}`,
    "",
    `### Branch\n${task.branchName ?? "(not yet created)"}`,
    task.baseBranch ? `\n### Base Branch\n${task.baseBranch}` : "",
    "",
    "## Previous Session Notes",
    previousNotes,
    "",
    "## Matched Skills / Rules",
    skillsLine,
    "",
    "## Recent Git History",
    "```",
    recentCommits,
    "```",
    "",
    "---",
    "_This file is auto-generated by vibe-code before each agent run._",
    "_Do NOT commit it — update your changes in the actual source files._",
  ]
    .filter((l) => l !== null)
    .join("\n");

  await writeFile(progressPath, progressContent, "utf8");

  // ── TASK.json ────────────────────────────────────────────────────────────
  const taskSnapshot = {
    id: task.id,
    title: task.title,
    status: task.status,
    branchName: task.branchName ?? null,
    baseBranch: task.baseBranch ?? null,
    parentTaskId: task.parentTaskId ?? null,
    tags: task.tags ?? [],
    runId: run.id,
    engine: run.engine,
    matchedSkills: matchedSkillNames,
  };

  await writeFile(taskJsonPath, JSON.stringify(taskSnapshot, null, 2), "utf8");

  return [progressPath, taskJsonPath];
}
